NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 85
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MODIFIER_THRESHOLD = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.05
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_FROM_DEFENDING = 15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.20
NDefines.NCountry.SHOGUN_INTERACTIONS_LEGITIMACY = 0

NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0.15 --- Reduced by 25%
NDefines.NCountry.PILLAGE_CAPITAL_DEVELOPMENT_DECREASE = 0.15 --- Reduced by 25% 
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0.4 --- 50% Goes to Capital
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0.4 --- 50% Goes to other State Provinces
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0.5 --- 50% Goes to Capital
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0.5 --- 50% Goes to other State Provinces
NDefines.NDiplomacy.REQUEST_HEIR_AE = 0

NDefines.NEconomy.BANKRUPTCY_DURATION = 10
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 15
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 25
NDefines.NCountry.ANCESTOR_COST = 150
NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500

NDefines.NMilitary.ARMY_ATTRITION_AT_COAST = 0.8
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 7.5
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 75
NDefines.NDiplomacy.SABOTAGE_REPUTATION_COST = 50
NDefines.NDiplomacy.STEAL_MAPS_COST = 50
NDefines.NDiplomacy.SUPPORT_REBELS_COST = 50
NDefines.NDiplomacy.SOW_DISCONTENT_COST = 85
NDefines.NDiplomacy.AGITATE_FOR_LIBERTY_COST = 60
NDefines.NDiplomacy.SABOTAGE_RECRUITMENT_COST = 70
NDefines.NDiplomacy.SLANDER_MERCHANTS_COST = 50
NDefines.NDiplomacy.CORRUPT_OFFICIALS_COST = 25		

NDefines.NMilitary.RAJPUT_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.COSSACK_BASE_COST_MODIFIER = 1.0