NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 100
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MODIFIER_THRESHOLD = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.05
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_FROM_DEFENDING = 15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.20
NDefines.NCountry.SHOGUN_INTERACTIONS_LEGITIMACY = 0

NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500
NDefines.NDiplomacy.REQUEST_HEIR_AE = 0

NDefines.NEconomy.BANKRUPTCY_DURATION = 10
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 15
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 25
NDefines.NCountry.ANCESTOR_COST = 150
NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500

NDefines.NMilitary.ARMY_ATTRITION_AT_COAST = 0.8
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 7.5
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 75
NDefines.NDiplomacy.SABOTAGE_REPUTATION_COST = 50
NDefines.NDiplomacy.STEAL_MAPS_COST = 50
NDefines.NDiplomacy.SUPPORT_REBELS_COST = 50
NDefines.NDiplomacy.SOW_DISCONTENT_COST = 85
NDefines.NDiplomacy.AGITATE_FOR_LIBERTY_COST = 60
NDefines.NDiplomacy.SABOTAGE_RECRUITMENT_COST = 70
NDefines.NDiplomacy.SLANDER_MERCHANTS_COST = 50
NDefines.NDiplomacy.CORRUPT_OFFICIALS_COST = 25		

NDefines.NMilitary.RAJPUT_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.COSSACK_BASE_COST_MODIFIER = 1.0

--
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_RELIGION = 135
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_TECHNOLOGY = 75
--
NDefines.NAI.AI_USES_HISTORICAL_IDEA_GROUPS	= 0
--
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 500.0


-- Deals with the final placement


--  New Changes Post AI
NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 15
NDefines.NMilitary.LOOTED_MAX = 8

NDefines.NGovernment.GOVERNMENT_REFORM_BASE_COST = 100.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_INCREASE = 50.0
NDefines.NGovernment.GOVERNMENT_REFORM_YEARLY_BASE_PROGRESS = 10.0
NDefines.NGovernment.GOVERNMENT_REFORM_HISTORIC_AUTONOMY = 0.25
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 50.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 50.0
NDefines.NGovernment.CENTRALIZE_STATE_STATE_COST_LIMIT = 1.0
NDefines.NGovernment.CENTRALIZE_STATE_REDUCTION = 20.0
NDefines.NGovernment.CENTRALIZE_STATE_YEARS = 1

NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 20

NDefines.NEconomy.EDICTS_DURATION_MONTHS = 0

NDefines.NAI.DEVELOPMENT_CAP_BASE = 15
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.80

NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_FAVOR_COST = 25
NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_REQUIRED_OPINION = 50
NDefines.NCountry.TRADE_FAVORS_FOR_MEN_FAVOR_COST = 25
NDefines.NCountry.TRADE_FAVORS_FOR_MEN_REQUIRED_OPINION = 50
NDefines.NCountry.TRADE_FAVORS_FOR_SAILORS_FAVOR_COST = 25
NDefines.NCountry.ROYAL_MARRIAGE_QUEEN_CHANCE = 100

NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.215
NDefines.NMilitary.MIN_MONTHLY_SAILORS = 65

-- Deals with Special Units
NDefines.NMilitary.STRELTSY_FIRE_DAMAGE_BONUS = 0.1
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = 0
NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 0
NDefines.NMilitary.JANISSARIES_USES_CONSTRUCTION = 0

NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_WE_CHANGE = -1
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.15

NDefines.NGovernment.COSSACKS_ABILITY_COSSACKS_SPAWN_SIZE = 0.15
NDefines.NGovernment.COSSACKS_ABILITY_COSSACKS_WE_CHANGE = -1

NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.49
NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 25
-- Post 1.32
NDefines.NMilitary.SLACKEN_AP_DROP = 0.02
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1.0

-- Post 1.33
NDefines.NMilitary.SCORCHED_DEVASTATION_IMPACT = 15
NDefines.NCountry.PS_SCORCH_EARTH = 10
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0.15
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = -25
NDefines.NCountry.PS_ASSAULT = 50
NDefines.NCountry.NEIGHBOURBONUS = -0.075
NDefines.NCountry.ABANDON_CORE_PRESTIGE = -5.0

NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_COST = 2.5
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_TREASURY_CONTRIBUTION = 0.10
NDefines.NReligion.BUY_INDULGENCE_COST = 0.75								
NDefines.NReligion.BUY_INDULGENCE_COST_EXCOMMUNICATE_MULTIPLIER = 2.0	
NDefines.NReligion.BUY_INDULGENCE_DURATION = 5							
NDefines.NReligion.BUY_INDULGENCE_TREASURY_CONTRIBUTION = 0.1			
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE = 5.0					
NDefines.NReligion.APPOINT_CARDINAL_CORRUPTION = 1.5						
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE_PAPAL_STATE = 1.0
NDefines.NReligion.APPOINT_CARDINAL_TOTAL_FACTOR = 3					
NDefines.NReligion.APPOINT_CARDINAL_COUNTRY_FACTOR = 25					
NDefines.NReligion.APPOINT_CARDINAL_MINIMUM_COST = 50.0					
NDefines.NReligion.PICK_GOLDEN_BULL_COST = 1000
NDefines.INVEST_PAPAL_INFLUENCE = 5.0
NDefines.NDiplomacy.CRUSADE_TIMEOUT_YEARS = 20			
NDefines.NCountry.COLONIAL_CLAIM_BONUS = 10
NDefines.NCountry.COLONIAL_CLAIM_VIOLATION = -15
NDefines.NCountry.COLONY_VIOLAION_PAPAL_INFLUENCE_COST  = -5		

NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.15
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.15		

-- Post 1.33.3
NDefines.NDiplomacy.TRIBUTE_BASE_CASH = 0.05
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.01
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.01
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.01
NDefines.NDiplomacy.TRIBUTE_REFUSED_TRUST = -1
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 3.0
NDefines.NDiplomacy.TRIBUTE_BASE_MANPOWER = 0.1
NDefines.NCountry.BREAK_TRIBUTARY_STABILITY_PENALTY = 0

NDefines.NCountry.MIN_POPULATION_FOR_TRADEGOOD_ASSIGNMENT = 50
NDefines.NMilitary.NATIVE_FEROCITY_IMPACT = 0.075
NDefines.NCountry.NATIVE_UPRISING_COOLDOWN_MONTHS = 18
NDefines.NCountry.NATIVE_UPRISING_CHANCE_PER_AGGRESSIVENESS = 1.5
NDefines.NCountry.PS_ATTACK_NATIVES = 7
NDefines.NEconomy.TREASURE_FLEET_INFLATION = 1.25
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7
NDefines.NCountry.MAX_FERVOR = 200.0
NDefines.NEconomy.EXPELLED_MINORITY_DEV_BONUS_FACTOR = 0.4
NDefines.NEconomy.EXPELLING_MINORITY_COLONIST_COST_FACTOR =  0.25
NDefines.NEconomy.EXPELLING_MINORITY_SETTLER_CHANCE_FACTOR = 0.002
NDefines.NReligion.EXPELLED_MINORITY_DURATION = 18250

-- Post 1.34 
NDefines.NMilitary.CAVALRY_COST = 15.0
NDefines.NMilitary.ARTILLERY_COST = 32.0