NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 100
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MODIFIER_THRESHOLD = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -5.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.05
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_FROM_DEFENDING = 15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.20
NDefines.NCountry.SHOGUN_INTERACTIONS_LEGITIMACY = 0

NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500
NDefines.NDiplomacy.REQUEST_HEIR_AE = 0

NDefines.NEconomy.BANKRUPTCY_DURATION = 10
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 15
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 25
NDefines.NCountry.ANCESTOR_COST = 150
NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 500

NDefines.NMilitary.ARMY_ATTRITION_AT_COAST = 0.8
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 7.5
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 75
NDefines.NDiplomacy.SABOTAGE_REPUTATION_COST = 50
NDefines.NDiplomacy.STEAL_MAPS_COST = 50
NDefines.NDiplomacy.SUPPORT_REBELS_COST = 50
NDefines.NDiplomacy.SOW_DISCONTENT_COST = 85
NDefines.NDiplomacy.AGITATE_FOR_LIBERTY_COST = 60
NDefines.NDiplomacy.SABOTAGE_RECRUITMENT_COST = 70
NDefines.NDiplomacy.SLANDER_MERCHANTS_COST = 50
NDefines.NDiplomacy.CORRUPT_OFFICIALS_COST = 25		

NDefines.NMilitary.RAJPUT_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.COSSACK_BASE_COST_MODIFIER = 1.0

--
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_RELIGION = 135
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_TECHNOLOGY = 75
--
NDefines.NAI.AI_USES_HISTORICAL_IDEA_GROUPS	= 0
--
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 500.0


-- Deals with the final placement


--  New Changes Post AI
NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 15
NDefines.NMilitary.LOOTED_MAX = 8

NDefines.NGovernment.GOVERNMENT_REFORM_BASE_COST = 100.0
NDefines.NGovernment.GOVERNMENT_REFORM_YEARLY_BASE_PROGRESS = 10.0
NDefines.NGovernment.GOVERNMENT_REFORM_HISTORIC_AUTONOMY = 0.25
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 50.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 50.0
NDefines.NGovernment.CENTRALIZE_STATE_STATE_COST_LIMIT = 1.0
NDefines.NGovernment.CENTRALIZE_STATE_REDUCTION = 20.0
NDefines.NGovernment.CENTRALIZE_STATE_YEARS = 1

NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 20

NDefines.NEconomy.EDICTS_DURATION_MONTHS = 0

NDefines.NAI.DEVELOPMENT_CAP_BASE = 15
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.80

NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_FAVOR_COST = 25
NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_REQUIRED_OPINION = 50
NDefines.NCountry.TRADE_FAVORS_FOR_MEN_FAVOR_COST = 25
NDefines.NCountry.TRADE_FAVORS_FOR_MEN_REQUIRED_OPINION = 50
NDefines.NCountry.TRADE_FAVORS_FOR_SAILORS_FAVOR_COST = 25
NDefines.NCountry.ROYAL_MARRIAGE_QUEEN_CHANCE = 100

NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.150
NDefines.NMilitary.MIN_MONTHLY_SAILORS = 65

-- Deals with Special Units
NDefines.NMilitary.STRELTSY_FIRE_DAMAGE_BONUS = 0.1
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = 0
NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 0
NDefines.NMilitary.JANISSARIES_USES_CONSTRUCTION = 0

NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_WE_CHANGE = -1
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.15

NDefines.NGovernment.COSSACKS_ABILITY_COSSACKS_SPAWN_SIZE = 0.15
NDefines.NGovernment.COSSACKS_ABILITY_COSSACKS_WE_CHANGE = -1

NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.49
NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 25
-- Post 1.32
NDefines.NMilitary.SLACKEN_AP_DROP = 0.03
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 0.80

-- Post 1.33
NDefines.NMilitary.SCORCHED_DEVASTATION_IMPACT = 15
NDefines.NCountry.PS_SCORCH_EARTH = 10
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0.15
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = -25
NDefines.NCountry.PS_ASSAULT = 50
NDefines.NCountry.NEIGHBOURBONUS = -0.075
NDefines.NCountry.ABANDON_CORE_PRESTIGE = -5.0

NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_COST = 2.5
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_TREASURY_CONTRIBUTION = 0.10
NDefines.NReligion.BUY_INDULGENCE_COST = 0.75								
NDefines.NReligion.BUY_INDULGENCE_COST_EXCOMMUNICATE_MULTIPLIER = 2.0	
NDefines.NReligion.BUY_INDULGENCE_DURATION = 5							
NDefines.NReligion.BUY_INDULGENCE_TREASURY_CONTRIBUTION = 0.1			
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE = 5.0					
NDefines.NReligion.APPOINT_CARDINAL_CORRUPTION = 1.5						
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE_PAPAL_STATE = 1.0
NDefines.NReligion.APPOINT_CARDINAL_TOTAL_FACTOR = 3					
NDefines.NReligion.APPOINT_CARDINAL_COUNTRY_FACTOR = 25					
NDefines.NReligion.APPOINT_CARDINAL_MINIMUM_COST = 50.0					
NDefines.NReligion.PICK_GOLDEN_BULL_COST = 1000
NDefines.INVEST_PAPAL_INFLUENCE = 5.0
NDefines.NDiplomacy.CRUSADE_TIMEOUT_YEARS = 20			
NDefines.NCountry.COLONIAL_CLAIM_BONUS = 10
NDefines.NCountry.COLONIAL_CLAIM_VIOLATION = -15
NDefines.NCountry.COLONY_VIOLAION_PAPAL_INFLUENCE_COST  = -5		

NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.15
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.15		

-- Post 1.33.3
NDefines.NDiplomacy.TRIBUTE_BASE_CASH = 0.05
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.01
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.01
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.01
NDefines.NDiplomacy.TRIBUTE_REFUSED_TRUST = -1
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 3.0
NDefines.NDiplomacy.TRIBUTE_BASE_MANPOWER = 0.1
NDefines.NCountry.BREAK_TRIBUTARY_STABILITY_PENALTY = 0

NDefines.NCountry.MIN_POPULATION_FOR_TRADEGOOD_ASSIGNMENT = 50
NDefines.NMilitary.NATIVE_FEROCITY_IMPACT = 0.075
NDefines.NCountry.NATIVE_UPRISING_COOLDOWN_MONTHS = 18
NDefines.NCountry.NATIVE_UPRISING_CHANCE_PER_AGGRESSIVENESS = 1.5
NDefines.NCountry.PS_ATTACK_NATIVES = 7
NDefines.NEconomy.TREASURE_FLEET_INFLATION = 1.25
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7
NDefines.NCountry.MAX_FERVOR = 200.0
NDefines.NEconomy.EXPELLED_MINORITY_DEV_BONUS_FACTOR = 0.4
NDefines.NEconomy.EXPELLING_MINORITY_COLONIST_COST_FACTOR =  0.25
NDefines.NEconomy.EXPELLING_MINORITY_SETTLER_CHANCE_FACTOR = 0.002
NDefines.NReligion.EXPELLED_MINORITY_DURATION = 18250

-- Post 1.34 
NDefines.NMilitary.CAVALRY_COST = 15.0
NDefines.NMilitary.ARTILLERY_COST = 32.0

NDefines.NMilitary.HEAVY_SHIP_COST = 40
NDefines.NMilitary.LIGHT_SHIP_COST = 22
NDefines.NMilitary.GALLEY_COST = 15
NDefines.NMilitary.TRANSPORT_COST = 10

NDefines.NEconomy.DEBASE_MAX_STORED_MONTHS = 24
NDefines.NEconomy.DEBASE_MONTHS_PER_CHARGE = 6
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 20
NDefines.NEconomy.DEBASE_ADDED_CORRUPTION = 1.5

NDefines.NReligion.PIETY_CORRUPTION = -1
NDefines.NReligion.PIETY_MANPOWER = 1
NDefines.NReligion.PIETY_COST = 0.25
NDefines.NReligion.PIETY_ABS_THRESHOLD = 0.50
NDefines.NReligion.PIETY_ACTION_COOLDOWN = 3
-- Lowered Action Cooldown to 3 years for now. Increase back to 5 if it breaks things

NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 0.75
NDefines.NCountry.PIETY_INCREASE_AT_GOOD_WAR = 0.15
NDefines.NCountry.PIETY_DECREASE_AT_BAD_WAR = -0.15


-- War Changes + Diplomacy Changes
	
NDefines.NDiplomacy.NUM_POSSIBLE_RIVALS = 3
NDefines.NDiplomacy.RIVAL_PRESTIGE_BONUS = 0.10
NDefines.NDiplomacy.RIVAL_SPY_OFFENCE = 0.10
NDefines.NDiplomacy.RIVAL_PEACE_COST_REDUCTION = -0.25
	
NDefines.NDiplomacy.AE_PROVINCE_CAP = 40
	
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 0.9					-- Demand a province (scales by province wealth, also used for annex)
NDefines.NDiplomacy.PEACE_COST_CONCEDE_PROVINCE = 0.9				-- Demand colonial area province concession.
NDefines.NDiplomacy.PEACE_COST_BECOME_VASSAL = 0.9					-- Vassalize a country (scales by province wealth)
NDefines.NDiplomacy.PEACE_COST_RETURN_CORE = 0.9						-- Return a core (scales by province wealth)
NDefines.NDiplomacy.PEACE_COST_REVOKE_CORE = 0.4						-- Revoke a core (scales by province wealth)
NDefines.NDiplomacy.PEACE_COST_RELEASE_ANNEXED = 0.9					-- Release annexed nation (scales by province wealth)
NDefines.NDiplomacy.PEACE_COST_RELEASE_VASSAL = 0.4					-- Release vassal (scales by province wealth)
NDefines.NDiplomacy.PEACE_COST_REVOKE_ELECTOR = 50					-- Revoke an elector title	
NDefines.NDiplomacy.PEACE_COST_UNION = 50 							-- _DDEF_PEACE_COST_UNION_ Peace cost for forming a personal union
NDefines.NDiplomacy.PEACE_COST_CONVERSION = 0.75					-- scaled with countrysize for forced conversion in peace.
NDefines.NDiplomacy.PEACE_COST_RELEASE = 2						-- _DDEF_PEACE_COST_RELEASE_ Base Peace cost for releasing an annexed country (also increases with nr of provinces)
NDefines.NDiplomacy.PEACE_COST_CONCEDE = 10 						-- _DDEF_PEACE_COST_CONCEDE_ Base Peace cost for conceding defeat
NDefines.NDiplomacy.PEACE_COST_GOLD_STEP = 1 						-- _DDEF_PEACE_COST_GOLD_STEP_ Peace Cost for 1 month of income
NDefines.NDiplomacy.PEACE_COST_ANNUL = 10 							-- _DDEF_PEACE_COST_ANNUL_ Peace cost for annulment of treaties
NDefines.NDiplomacy.PEACE_COST_CHANGE_GOVERNMENT = 25			-- _Peace cost for changing government form
NDefines.NDiplomacy.PEACE_COST_TRADE_POWER = 60					-- Peace cost for demanding trade power
NDefines.NDiplomacy.PEACE_COST_INDEPENDANCE = 30				-- Peace cost for breaking free of union
NDefines.NDiplomacy.PEACE_COST_ENFORCED_FLEET_BASING_RIGHTS = 15   -- Peace cost for enforced fleet basing righs
NDefines.NDiplomacy.PEACE_COST_ENFORCED_MILITARY_ACCESS = 10       -- Peace cost for enforced military access
NDefines.NDiplomacy.PEACE_COST_WAR_REPARATIONS = 10				-- Peace cost for war reparations
NDefines.NDiplomacy.PEACE_COST_GIVE_UP_CLAIM = 15					-- Peace cost for giving up all claims in a country
NDefines.NDiplomacy.PEACE_COST_DISMANTLE_REVOLUTION = 100
NDefines.NDiplomacy.PEACE_COST_CHANGE_HRE_RELIGION = 100
NDefines.NDiplomacy.PEACE_COST_HUMILIATE_RIVAL = 40
NDefines.NDiplomacy.PEACE_COST_FORCE_MIGRATION = 100.0
NDefines.NDiplomacy.PEACE_COST_ENFORCE_REBEL_DEMANDS = 50
NDefines.NDiplomacy.PEACE_COST_END_RIVALRY = 25
NDefines.NDiplomacy.PEACE_COST_TAKE_MANDATE = 40
NDefines.NDiplomacy.MAX_PEACE_COST_TRIBUTARY_STATE = 80
NDefines.NDiplomacy.MAX_PEACE_COST_CANCEL_SUBJECT = 100
	
	
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_AE = 0.65 				-- _DDEF_PO_DEMAND_PROVINCES_AE = 10, (Per development)
NDefines.NDiplomacy.PO_RETURN_CORES_AE = 0.4 					-- (Per core, only applied if returning cores to vassals of winner)
NDefines.NDiplomacy.PO_FORM_PU_AE = 0.15						-- _DDEF_PO_FORM_PU_AE = 10, (Per development)
NDefines.NDiplomacy.PO_CONCEDE_COLONIAL_AE = 0.20
NDefines.NDiplomacy.PO_BECOME_VASSAL_AE = 0.4 					-- _DDEF_PO_BECOME_VASSAL_AE = 10, (Per development)
NDefines.NDiplomacy.PO_TRANSFER_VASSAL_AE = 0.25
NDefines.NDiplomacy.PO_ANNEX_PRESTIGE = 0.20 						-- _DDEF_PO_ANNEX_PRESTIGE = 10, (No effect on loser :)
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_PRESTIGE = 0.20				-- _DDEF_PO_DEMAND_PROVINCES_PRESTIGE = 10, (Per development)
NDefines.NDiplomacy.PO_REVOKE_CORES_PRESTIGE = 0.1					-- _DDEF_PO_REVOKE_CORES_PRESTIGE = 10, (Per development)
NDefines.NDiplomacy.PO_RETURN_CORES_PRESTIGE = 0.20					-- (Per development)
NDefines.NDiplomacy.PO_RELEASE_VASSAL_PRESTIGE = 0.20				-- _DDEF_PO_RELEASE_VASSAL_PRESTIGE = 10,
NDefines.NDiplomacy.PO_TRANSFER_VASSAL_PRESTIGE = 0.20
NDefines.NDiplomacy.PO_RELEASE_ANNEXED_PRESTIGE = 0.20 				-- _DDEF_PO_RELEASE_ANNEXED_PRESTIGE = 10, (Per released province)
NDefines.NDiplomacy.PO_CHANGE_RELIGION_PRESTIGE = 6 				-- _DDEF_PO_CHANGE_RELIGION_PRESTIGE = 10,
NDefines.NDiplomacy.PO_FORM_PU_PRESTIGE = 0.10 						-- _DDEF_PO_FORM_PU_PRESTIGE = 10,
NDefines.NDiplomacy.PO_BECOME_VASSAL_PRESTIGE = 0.15 					-- _DDEF_PO_BECOME_VASSAL_PRESTIGE = 10,
NDefines.NDiplomacy.PO_CONCEDE_DEFEAT_PRESTIGE = 25				-- _DDEF_PO_CONCEDE_DEFEAT_PRESTIGE_
NDefines.NDiplomacy.PO_DISMANTLE_REVOLUTION_PRESTIGE = 100
NDefines.NDiplomacy.PO_CHANGE_HRE_RELIGION_PRESTIGE = 100
NDefines.NDiplomacy.PO_ANNUL_TREATY_PRESTIGE = 0.5					-- _DDEF_PO_ANNUL_TREATY_PRESTIGE = 10,
NDefines.NDiplomacy.PO_REVOKE_ELECTOR_AE = 20
NDefines.NDiplomacy.PO_REVOKE_ELECTOR_PRESTIGE = 4
NDefines.NDiplomacy.PO_TRADE_POWER_PRESTIGE = 1
NDefines.NDiplomacy.PO_CONCEDE_COLONIAL_PRESTIGE = 2.5
NDefines.NDiplomacy.PO_GIVE_UP_CLAIM_PRESTIGE = 3
NDefines.NDiplomacy.PO_HUMILIATE_RIVAL_PRESTIGE = 4
NDefines.NDiplomacy.PO_FORCE_MIGRATION_PRESTIGE = 1
NDefines.NDiplomacy.PO_ENFORCE_REBEL_DEMANDS_PRESTIGE = 3
NDefines.NDiplomacy.PO_TAKE_MANDATE_PRESTIGE = 15
NDefines.NDiplomacy.PO_TAKE_MANDATE_AE = 0
	
NDefines.NDiplomacy.PO_ENFORCE_FLEET_BASING_PRESTIGE = 3
NDefines.NDiplomacy.PO_ENFORCE_MIL_ACCESS_PRESTIGE = 3
NDefines.NDiplomacy.PO_WAR_REPARATIONS_PRESTIGE = 3
NDefines.NDiplomacy.PO_END_RIVALRY_PRESTIGE = 3
NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.25
	
NDefines.NDiplomacy.HEGEMONY_MONTHLY_PROGRESS = 1	

NDefines.NReligion.CONSECRATE_PATRIACH_AUTHORITY_BOOST = 0.05
NDefines.NReligion.CONSECRATE_PATRIARCH_THRESHOLD = 25
NDefines.NReligion.ORTHODOX_ICON_DURATION_MONTHS = 300
NDefines.NReligion.ORTHODOX_ICON_AUTHORITY_COST = 0.2
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 120
NDefines.NGovernment.GOVERNMENT_REFORM_COST_INCREASE = 40.0

NDefines.NCountry.EXPLOIT_ADM_INCOME = 48