NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 50
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 135
--
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 1000.0
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT	= 0.45
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 9.0
NDefines.NAI.PURSUE_DISTANCE = 90.0
--
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 1.9
NDefines.NAI.INVADING_BRAVERY = 1.275
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 12
--
NDefines.NAI.WAR_WARSCORE_TO_JOIN = -100
NDefines.NAI.WAR_MIN_WARSCORE_TO_JOIN = -5
--
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 20.0
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.125
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 80
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 40
--
NDefines.NAI.TRANSPORT_FRACTION = 0.45
NDefines.NAI.BIGSHIP_FRACTION = 0.25
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 100.0
NDefines.NAI.ARTILLERY_FRACTION = 0.35
NDefines.NAI.MIN_CAV_PERCENTAGE = 9.0
NDefines.NAI.MAX_CAV_PERCENTAGE = 40
NDefines.NAI.REGIMENTS_PER_GENERAL = 24
NDefines.NAI.ONLY_INFANTRY_MERCS = 1
--
NDefines.NAI.BASE_CAN_MAKE_CORE_DESIRE_TO_RETURN_PROVINCE = 15
--
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.05
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_FRIEND_IN_COMBAT = 0.45
NDefines.NAI.ACCEPTABLE_BALANCE_MULT_OFFENSIVE = 0.55
--
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.025
--
