NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 42.0
NDefines.NAI.MAX_SAVINGS = 150.0
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.60
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.25
NDefines.NAI.DESIRED_DEFICIT = 0.135
NDefines.NAI.DESIRED_SURPLUS = 0.15
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 3.0
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 24.0
--
NDefines.NAI.DEBASE_THRESHOLD = 3500
--
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.38
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 60
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 3
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 50.0
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 25.0
--
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.1
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.2
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.85
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.20
NDefines.NAI.FORT_BUDGET_FRACTION = 0.185
--
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 1800.0
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1000.0
--
NDefines.NAI.UPGRADE_CENTER_OF_TRADE_BASE_AI_DESIRE = 75.0
--
NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.3
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.175
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 1.2
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 0.95
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 1.55
NDefines.NAIEconomy.MISSIONARY_FRACTION = 0.1
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.0
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 1.3
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 1.2
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 1.0
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 1.2
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 0.9
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 0.7
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 1.6