NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 105
--
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 50
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT	= 0.6
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 5.75
NDefines.NAI.PURSUE_DISTANCE = 90
--
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 1.3
NDefines.NAI.INVADING_BRAVERY = 1.35
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 10
--
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 5.2
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.1
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 162
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 120
--
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 75
NDefines.NAI.ARTILLERY_FRACTION = 0.40
NDefines.NAI.MIN_CAV_PERCENTAGE = 5
NDefines.NAI.MAX_CAV_PERCENTAGE = 40
NDefines.NAI.REGIMENTS_PER_GENERAL = 31
NDefines.NAI.ONLY_INFANTRY_MERCS = 0
--
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.3
--
NDefines.NAI.IMPORTANT_PROVINCE_THRESHOLD = 0.035
--
